import json
import os

surahs = [
    (1, "Fâtiha", "الفاتحة", 5, "erken_mekke", 7, "Açılış, başlangıç, Kur’an’ın özü"),
    (2, "Bakara", "البقرة", 87, "medine", 286, "İnek, toplumsal hukuk, itikat ve şeriat esasları"),
    (3, "Âl-i İmrân", "آل عمران", 89, "medine", 200, "İmran ailesi, tevhid, Uhud savaşı ve sabır"),
    (4, "Nisâ", "النساء", 92, "medine", 176, "Kadınlar, aile hukuku, adalet ve emanet"),
    (5, "Mâide", "المائدة", 112, "medine", 120, "Sofra, ahitler, helal-haram ve kardeşlik"),
    (6, "En'âm", "الأنعام", 55, "gec_mekke", 165, "Kurban ve ehil hayvanlar, tefekkür, tevhid"),
    (7, "A'râf", "الأعراف", 39, "gec_mekke", 206, "Yüksek mevkiler, peygamberler tarihi ve ibret"),
    (8, "Enfâl", "الأنفال", 88, "medine", 75, "Savaş ganimetleri, Bedir zaferi ve sadakat"),
    (9, "Tevbe", "التوبة", 113, "medine", 127, "Tövbe, nifakla mücadele ve samimiyet"),
    (10, "Yûnus", "يونس", 51, "gec_mekke", 109, "Yunus peygamber, vahiy ve ilahi rahmet"),
    (11, "Hûd", "هود", 52, "gec_mekke", 123, "Hud peygamber, kavimlerin helaki ve istikamet"),
    (12, "Yûsuf", "يوسف", 53, "gec_mekke", 111, "Yusuf peygamber, ahsenü'l-kasas (kıssaların en güzeli)"),
    (13, "Ra'd", "الرعد", 96, "medine", 43, "Gök gürültüsü, kevni ayetler ve hakikat"),
    (14, "İbrâhîm", "إبراهيم", 72, "gec_mekke", 52, "İbrahim peygamber, tevhid ve şükür"),
    (15, "Hicr", "الحجر", 54, "gec_mekke", 99, "Hicr vadisi, Kur'an'ın korunması"),
    (16, "Nahl", "النحل", 70, "gec_mekke", 128, "Bal arısı, ilahi nimetler ve tefekkür"),
    (17, "İsrâ", "الإسراء", 50, "gec_mekke", 111, "Gece yürüyüşü, Miraç ve ahlaki ilkeler"),
    (18, "Kehf", "الكهف", 69, "orta_mekke", 110, "Mağara arkadaşları, fitneler ve hikmet"),
    (19, "Meryem", "مريم", 44, "erken_mekke", 98, "Hz. Meryem, Zekeriya ve İsa mucizesi"),
    (20, "Tâhâ", "طه", 45, "erken_mekke", 135, "Taha, Hz. Musa'nın risaleti ve tebliğ"),
    (21, "Enbiyâ", "الأنبياء", 73, "orta_mekke", 112, "Peygamberler ve ortak tevhid çağrısı"),
    (22, "Hac", "الحج", 103, "medine", 78, "Hac ibadeti, kıyamet ve kurban"),
    (23, "Mü'minûn", "المؤمنون", 74, "orta_mekke", 118, "Müminlerin vasıfları ve kurtuluş"),
    (24, "Nûr", "النور", 102, "medine", 64, "İlahi nur, iffet ve toplumsal ahlak"),
    (25, "Furkân", "الفرقان", 42, "orta_mekke", 77, "Hak ile batılı ayıran ölçü"),
    (26, "Şuarâ", "الشعراء", 47, "orta_mekke", 227, "Şairler, peygamberlerin mücadelesi"),
    (27, "Neml", "النمل", 48, "orta_mekke", 93, "Karınca, Süleyman peygamber ve Belkıs"),
    (28, "Kasas", "القصص", 49, "orta_mekke", 88, "Tarihi kıssalar, Musa ve Firavun"),
    (29, "Ankebût", "العنكبوت", 85, "gec_mekke", 69, "Örümcek ağı misali, imtihan"),
    (30, "Rûm", "الروم", 84, "gec_mekke", 60, "Bizanslılar, tarihin akışı ve kevnî ayetler"),
    (31, "Lokmân", "لقمان", 57, "orta_mekke", 34, "Lokman hekimin oğluna öğütleri, hikmet"),
    (32, "Secde", "السجدة", 75, "orta_mekke", 30, "Secde, yaratılış ve diriliş"),
    (33, "Ahzâb", "الأحزاب", 90, "medine", 73, "Gruplar, Hendek savaşı ve Hz. Peygamber'in konumu"),
    (34, "Sebe'", "سبإ", 58, "orta_mekke", 54, "Sebe kavmi, şükür ve nankörlük"),
    (35, "Fâtır", "فاطر", 43, "orta_mekke", 45, "Yaratan, melekler ve ilahi kudret"),
    (36, "Yâsîn", "يس", 41, "orta_mekke", 83, "Kur'an'ın kalbi, diriliş ve tebliğ"),
    (37, "Sâffât", "الصافات", 56, "orta_mekke", 182, "Sıra sıra dizilenler, melekler ve tevhid"),
    (38, "Sâd", "ص", 38, "orta_mekke", 88, "Sad harfi, peygamberlerin imtihanı"),
    (39, "Zümer", "الزمر", 59, "gec_mekke", 75, "Zümreler, ihlas ve Allah'ın rahmeti"),
    (40, "Mü'min (Gâfir)", "غافر", 60, "gec_mekke", 85, "Bağışlayan, Firavun ailesinden inanan adam"),
    (41, "Fussilet", "فصلت", 61, "gec_mekke", 54, "Ayrıntılı açıklanmış ayetler"),
    (42, "Şûrâ", "الشورى", 62, "gec_mekke", 53, "İstişare ve vahyin mahiyeti"),
    (43, "Zuhruf", "الزخرف", 63, "gec_mekke", 89, "Altın süs, dünya hayatının faniliği"),
    (44, "Duhân", "الدخان", 64, "gec_mekke", 59, "Duman, kıyamet alameti"),
    (45, "Câsiye", "الجاثية", 65, "gec_mekke", 37, "Diz çökenler, mahşer günü dehşeti"),
    (46, "Ahkâf", "الأحقاف", 66, "gec_mekke", 35, "Kum tepeleri, Ad kavmi"),
    (47, "Muhammed", "محمد", 95, "medine", 38, "Hz. Muhammed, cihat ve teslimiyet"),
    (48, "Fetih", "الفتح", 111, "medine", 29, "Hudeybiye barışı ve açık fetih"),
    (49, "Hucurât", "الحجرات", 106, "medine", 18, "Odalar, ahlak ve mümin kardeşliği"),
    (50, "Kâf", "ق", 34, "erken_mekke", 45, "Kaf harfi, diriliş ve ölüm"),
    (51, "Zâriyât", "الذاريات", 67, "erken_mekke", 60, "Esip savuran rüzgarlar"),
    (52, "Tûr", "الطور", 76, "orta_mekke", 49, "Tur dağı, ahiret sahneleri"),
    (53, "Necm", "النجم", 23, "erken_mekke", 62, "Kayan yıldız, miraç ve vahiy"),
    (54, "Kamer", "القمر", 37, "erken_mekke", 55, "Ay, kıyametin yakınlığı"),
    (55, "Rahmân", "الرحمن", 97, "medine", 78, "Sonsuz merhamet sahibi ve nimetleri"),
    (56, "Vâkıa", "الواقعة", 46, "erken_mekke", 96, "Kaçınılmaz kıyamet ve 3 sınıf insan"),
    (57, "Hadîd", "الحديد", 94, "medine", 29, "Demir, infak ve iman"),
    (58, "Mücâdele", "المجادلة", 105, "medine", 22, "Hakkını arayan kadın, gizli konuşmalar"),
    (59, "Haşr", "الحشر", 101, "medine", 24, "Sürgün, Medine muhasarası ve Esmâü'l-Hüsnâ"),
    (60, "Mümtehine", "الممتحنة", 91, "medine", 13, "Sınanan kadın, dostluk sınırları"),
    (61, "Saff", "الصف", 109, "medine", 14, "Saflar, söz ile amel tutarlılığı"),
    (62, "Cuma", "الجمعة", 110, "medine", 11, "Cuma namazı, Kitap ehli meseli"),
    (63, "Münâfikûn", "المنافقون", 104, "medine", 11, "Münafıkların psikolojisi ve tavırları"),
    (64, "Tegâbün", "التغابن", 108, "medine", 18, "Kazanma ve kaybetme günü"),
    (65, "Talâk", "الطلاق", 99, "medine", 12, "Boşanma hukuku ve takva"),
    (66, "Tahrîm", "التحريم", 107, "medine", 12, "Haram kılma, aile mahremiyeti"),
    (67, "Mülk", "الملك", 77, "orta_mekke", 30, "Mülk ve hakimiyet, ölüm ve hayat imtihanı"),
    (68, "Kalem", "القلم", 2, "erken_mekke", 52, "Kalem, peygamberin yüce ahlakı"),
    (69, "Hâkka", "الحاقة", 78, "orta_mekke", 52, "Gerçekleşecek kıyamet"),
    (70, "Meâric", "المعارج", 79, "orta_mekke", 44, "Yükseliş dereceleri"),
    (71, "Nûh", "نوح", 71, "orta_mekke", 28, "Nuh peygamberin tebliği ve duası"),
    (72, "Cin", "الجن", 40, "orta_mekke", 28, "Cinlerin Kur'an dinlemesi ve tevhidi"),
    (73, "Müzzemmil", "المزمل", 3, "erken_mekke", 20, "Örtünen, gece ibadeti"),
    (74, "Müddessir", "المدثر", 4, "erken_mekke", 56, "Bürünen, kalk ve uyar"),
    (75, "Kıyâme", "القيامة", 31, "erken_mekke", 40, "Kıyamet ve insanın kendini kınaması"),
    (76, "İnsân", "الإنسان", 98, "medine", 31, "İnsanın varoluşu ve cennet nimetleri"),
    (77, "Mürselât", "المرسلات", 33, "erken_mekke", 50, "Gönderilen rüzgarlar ve melekler"),
    (78, "Nebe'", "النبإ", 80, "erken_mekke", 40, "Büyük haber, diriliş"),
    (79, "Nâziât", "النازعات", 81, "erken_mekke", 46, "Söküp çıkaranlar, ölüm"),
    (80, "Abese", "عبس", 24, "erken_mekke", 42, "Yüzünü ekşitti, insana saygı"),
    (81, "Tekvîr", "التكوير", 7, "erken_mekke", 29, "Güneşin dürülmesi"),
    (82, "İnfitâr", "الانفطار", 82, "erken_mekke", 19, "Göğün yarılması"),
    (83, "Mutaffifîn", "المطففين", 86, "gec_mekke", 36, "Ölçüde hile yapanlar"),
    (84, "İnşikâk", "الانشقاق", 83, "erken_mekke", 25, "Göğün parçalanması"),
    (85, "Bürûc", "البروج", 27, "erken_mekke", 22, "Burçlar, Ashab-ı Uhdud"),
    (86, "Târık", "الطارق", 36, "erken_mekke", 17, "Sabah yıldızı, insanın yaratılışı"),
    (87, "A'lâ", "الأعلى", 8, "erken_mekke", 19, "En yüce olan, tesbih"),
    (88, "Gâşiye", "الغاشية", 68, "erken_mekke", 26, "Kuşatıp kaplayan felaket"),
    (89, "Fecr", "الفجر", 10, "erken_mekke", 30, "Tan yeri, geçmiş kavimler"),
    (90, "Beled", "البلد", 35, "erken_mekke", 20, "Şehir (Mekke), sarp yokuş"),
    (91, "Şems", "الشمس", 26, "erken_mekke", 15, "Güneş, nefsi arındırma"),
    (92, "Leyl", "الليل", 9, "erken_mekke", 21, "Gece, cömertlik ve cimrilik"),
    (93, "Duhâ", "الضحى", 11, "erken_mekke", 11, "Kuşluk vakti, ilahi teselli"),
    (94, "İnşirâh", "الشرح", 12, "erken_mekke", 8, "Gönül ferahlığı"),
    (95, "Tîn", "التين", 28, "erken_mekke", 8, "İncir, insanın ahsen-i takvim yaratılışı"),
    (96, "Alak", "العلق", 1, "erken_mekke", 19, "İlk vahiy: Oku"),
    (97, "Kadir", "القدر", 25, "erken_mekke", 5, "Kadir gecesi ve vahyin inişi"),
    (98, "Beyyine", "البينة", 100, "medine", 8, "Açık delil, dinin özü"),
    (99, "Zilzâl", "الزلزلة", 93, "medine", 8, "Büyük sarsıntı"),
    (100, "Âdiyât", "العاديات", 14, "erken_mekke", 11, "Koşan atlar, insanın nankörlüğü"),
    (101, "Kâria", "القارعة", 30, "erken_mekke", 11, "Yürekleri hoplatan kıyamet"),
    (102, "Tekâsür", "التكاثر", 16, "erken_mekke", 8, "Çoklukla övünme tutkusu"),
    (103, "Asr", "العصر", 13, "erken_mekke", 3, "Zaman, kurtuluşun 4 şartı"),
    (104, "Hümeze", "الهمزة", 32, "erken_mekke", 9, "Dedikodu ve mal biriktirme"),
    (105, "Fîl", "الفيل", 19, "erken_mekke", 5, "Fil ordusu ve Kabe'nin korunması"),
    (106, "Kureyş", "قريش", 29, "erken_mekke", 4, "Kureyş kabilesi ve güven nimeti"),
    (107, "Mâûn", "الماعون", 17, "erken_mekke", 7, "Yardım, gösteriş ve yetimi itme"),
    (108, "Kevser", "الكوثر", 15, "erken_mekke", 3, "Bitmez tükenmez hayır ve nimet"),
    (109, "Kâfirûn", "الكافرون", 18, "erken_mekke", 6, "İnançta uzlaşmazlık, sizin dininiz size"),
    (110, "Nasr", "النصر", 114, "medine", 3, "İlahi yardım ve fetih"),
    (111, "Tebbet (Mesed)", "المسد", 6, "erken_mekke", 5, "Ebu Leheb'in elleri kurusun"),
    (112, "İhlâs", "الإخلاص", 22, "erken_mekke", 4, "Tevhidin katıksız ifadesi"),
    (113, "Felak", "الفلق", 20, "erken_mekke", 5, "Sabahın aydınlığına sığınma"),
    (114, "Nâs", "الناس", 21, "erken_mekke", 6, "İnsanların Rabbine sığınma")
]

os.makedirs("data-pipeline/scripts", exist_ok=True)
metadata = []
for s in surahs:
    metadata.append({
        "id": s[0],
        "ad_tr": s[1],
        "ad_ar": s[2],
        "nuzul_sirasi": s[3],
        "donem": s[4],
        "ayet_sayisi": s[5],
        "aciklama": s[6]
    })

output_path = "data-pipeline/scripts/surah-metadata.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(metadata, f, ensure_ascii=False, indent=2)

print(f"Başarıyla oluşturuldu: {output_path} ({len(metadata)} sure)")
